# -*- coding: utf-8 -*-
"""Copy of CVAndBatchReading (-1 and 1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ns6wa_IDO8npTr_AO0b-6-Wg-4RFmrTs
"""

# !pip install PyDrive
import pandas as pd
import numpy as np
import random
import os
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive1 = GoogleDrive(gauth)
from google.colab import drive
drive.mount('/content/drive')

# downloaded = drive1.CreateFile({'id':"1nkssrQFAs3a2xjnWEL0ksKXeV2F3dutL"})   # replace the id with id of file you want to access
# downloaded.GetContentFile('drug_drug_matrix.csv')        # replace the file name with your file

# pd.read_csv('drug_drug_matrix.csv')

downloaded = drive1.CreateFile({'id':"1CTRwQ1LXFdBsDVtDPs8FNRAqKAK1c95k"})   # replace the id with id of file you want to access
downloaded.GetContentFile('triple_cosineSNF(-1and1)1.csv') 
data = pd.read_csv('triple_cosineSNF(-1and1)1.csv').iloc[:,1:]
# index = list(range(len(data)))
# random.shuffle(index)
# dataShuffled =  data.iloc[index]
# data.to_csv('../../triple_cosineSNF(-1and1)1.csv')

# (data.iloc[:,:3]).to_csv('drugsPairs(-1_1).csv')

# drugsPairs = pd.read_csv('drugsPairs(-1_1).csv')
# r, c = drugsPairs.shape
# print(r, c)

# indexes = []
# for i in range(21351):
#     candInd = np.random.randint(r)
# #     if (len(indexes)< r-1):
#     if (candInd not in indexes):
#         indexes.append(candInd)
# #         print(candInd)
#     else:
#         while(True):
#             candInd = np.random.randint(r)
#             if candInd not in indexes:
#                 break
#         indexes.append(candInd)
# #         print(candInd)
#     di, dj = str(drugsPairs.iloc[candInd,1]), str(drugsPairs.iloc[candInd,2])
# #     print(di,dj)
#     bufpairs = drugsPairs[drugsPairs[str(1)]==dj]
#     indexes.append(int(bufpairs[bufpairs[str(2)]==di]['0']))

# print(len(indexes))

# index = drugsPairs.values[:,0]
# random.shuffle(index)
# drugsPairsShuffled =  drugsPairs.iloc[index]

# checked = False
# problems = []
# i = 0
# while(i +1 < len(indexes)):
# #     if i + 1 == len(indexes):
#     if (drugsPairs.iloc[indexes[i],1]==drugsPairs.iloc[indexes[i+1],2])and(drugsPairs.iloc[indexes[i],2]==drugsPairs.iloc[indexes[i+1],1]):
#         i += 2

#     else:        
#         problems.append([i,drugsPairs.iloc[i,:]])
# #         print([i,drugsPairs.iloc[i,:]])
#         del indexes[i]
# #         i += 1
# #         if i + 1 == len(indexes):
# #             problems.append(list(i,drugsPairs.iloc[i,:]))
# #             indexes.remove(i)

# len(problems)

# [20,drugsPairs.iloc[20,:]]

# problems = pd.DataFrame(problems)
# problems.to_csv('problems21351.csv', index=False)

# indexes = pd.DataFrame(indexes)
# indexes.to_csv('indexes21351.csv', index=False)

# indexes = pd.read_csv('indexes21351.csv')
# indexes = list(indexes['0'])
# # print(indexes[0]==122943)

# data10000 = []
# line1 = 0
# with open('../../saved F(triple_cosineSNF).csv', 'r') as fd:
    
#     for row ,line in enumerate(fd):
#         if row-1 in indexes:
# #             print(row)
#             data10000.append(line.split(','))
# #         line1 = line.split(',')
# #         break
# # line1

# downloaded = drive.CreateFile({'id':"1EbjypymyTvQL9LtWtYMA8Q31y6RLm9P7"})   # replace the id with id of file you want to access
# downloaded.GetContentFile('triple_cosineSNF(-1and1).csv')ta
len(dataAll['0'])* 0.8

dataAll = data
indexes = pd.read_csv('triple_cosineSNF(-1and1)1.csv').iloc[:,0]

data = []
officer = []
index = indexes
random.shuffle(index)
for i in range(34000):
    if i in officer:
        continue
    data.append(dataAll.iloc[i,:])
    officer.append(i)
    # bufpairs = dataAll[dataAll[str(0)]==dataAll.iloc[i,1]]
    # data.append(bufpairs[bufpairs[str(1)]==dataAll.iloc[i,0]])
    for j in index:
        if j in officer:
            continue
#         print('add')
        if dataAll.iloc[i,1] == dataAll.iloc[j,0] and dataAll.iloc[i,0] == dataAll.iloc[j,1]:
            data.append(dataAll.iloc[j,:])
            officer.append(j)
            break
    # officer.append(int(bufpairs.index[bufpairs[str(1)]==dataAll.iloc[i,0]][0]))
            
data = pd.DataFrame(data)
data.to_csv('/content/drive/My Drive/Colab Notebooks/tripleTrain.csv', index=False)
dataAll.drop(officer, inplace=True)
dataAll.to_csv('/content/drive/My Drive/Colab Notebooks/tripleTest.csv', index=False)
# from google.colab import files
# data.to_csv('triple(-1and1).csv') 
# files.download('triple(-1and1).csv')

data = pd.DataFrame(data)
data.to_csv('/content/drive/My Drive/Colab Notebooks/triple(-1and1).csv', index=False)
# from google.colab import files
# data.to_csv('/content/drive/My Drive/Colab Notebooks/triple(-1and1).csv') 
# files.download('/content/drive/My Drive/Colab Notebooks/triple(-1and1).csv')

from google.colab import files
df.to_csv('triple(-1and1).csv') 
files.download('triple(-1and1).csv')

import pandas as pd
df = pd.DataFrame({'name':['Bob','Jen','Tim'],
                   'age':[20,30,40],
                   'pet':['cat', 'dog', 'bird']})
off = [1]

df.to_csv('/content/drive/My Drive/Colab Notebooks/hg.csv')

df.drop(off, inplace=True)

df

